// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// K-Sprint 21 — AI-Kernel-Subsystem (Aurora AI)
use alloc::collections::BTreeMap; use alloc::vec::Vec; use alloc::string::{String,ToString}; use alloc::sync::Arc; use spin::Mutex;
#[derive(Clone,Debug)] pub struct Tensor{pub shape:Vec<usize>,pub data:Vec<f64>,pub dtype:TensorDtype}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum TensorDtype{F64,F32,F16,I32,I8}
impl Tensor{pub fn new(shape:Vec<usize>,data:Vec<f64>)->Self{Tensor{shape,data,dtype:TensorDtype::F64}}pub fn scalar(v:f64)->Self{Tensor{shape:vec![],data:vec![v],dtype:TensorDtype::F64}}pub fn zeros(s:Vec<usize>)->Self{let n=s.iter().product::<usize>().max(1);Tensor{shape:s,data:vec![0.0;n],dtype:TensorDtype::F64}}pub fn from_vec(d:Vec<f64>)->Self{let s=vec![d.len()];Tensor{shape:s,data:d,dtype:TensorDtype::F64}}pub fn rank(&self)->usize{self.shape.len()}pub fn size(&self)->usize{self.data.len()}
pub fn add(&self,o:&Tensor)->Result<Tensor,AiError>{if self.shape!=o.shape{return Err(AiError::ShapeMismatch);}Ok(Tensor{shape:self.shape.clone(),data:self.data.iter().zip(&o.data).map(|(a,b)|a+b).collect(),dtype:self.dtype})}
pub fn mul(&self,o:&Tensor)->Result<Tensor,AiError>{if self.shape!=o.shape{return Err(AiError::ShapeMismatch);}Ok(Tensor{shape:self.shape.clone(),data:self.data.iter().zip(&o.data).map(|(a,b)|a*b).collect(),dtype:self.dtype})}
pub fn scale(&self,s:f64)->Tensor{Tensor{shape:self.shape.clone(),data:self.data.iter().map(|a|a*s).collect(),dtype:self.dtype}}
pub fn matmul(&self,o:&Tensor)->Result<Tensor,AiError>{if self.rank()!=2||o.rank()!=2{return Err(AiError::InvalidShape("matmul 2D".into()));}let(m,k,k2,n)=(self.shape[0],self.shape[1],o.shape[0],o.shape[1]);if k!=k2{return Err(AiError::ShapeMismatch);}let mut r=vec![0.0;m*n];for i in 0..m{for j in 0..n{let mut s=0.0;for x in 0..k{s+=self.data[i*k+x]*o.data[x*n+j];}r[i*n+j]=s;}}Ok(Tensor{shape:vec![m,n],data:r,dtype:self.dtype})}
pub fn relu(&self)->Tensor{Tensor{shape:self.shape.clone(),data:self.data.iter().map(|a|a.max(0.0)).collect(),dtype:self.dtype}}
pub fn sigmoid(&self)->Tensor{Tensor{shape:self.shape.clone(),data:self.data.iter().map(|a|1.0/(1.0+(-a).exp())).collect(),dtype:self.dtype}}
pub fn softmax(&self)->Result<Tensor,AiError>{if self.rank()!=1&&self.rank()!=2{return Err(AiError::InvalidShape("softmax 1D/2D".into()));}if self.rank()==1{let mx=self.data.iter().cloned().fold(0.0f64,f64::max);let e:Vec<f64>=self.data.iter().map(|a|(a-mx).exp()).collect();let s:f64=e.iter().sum();Ok(Tensor{shape:self.shape.clone(),data:e.iter().map(|x|x/s).collect(),dtype:self.dtype})}else{let(r,c)=(self.shape[0],self.shape[1]);let mut d=vec![0.0;r*c];for i in 0..r{let row=&self.data[i*c..(i+1)*c];let mx=row.iter().cloned().fold(0.0f64,f64::max);let e:Vec<f64>=row.iter().map(|a|(a-mx).exp()).collect();let s:f64=e.iter().sum();for j in 0..c{d[i*c+j]=e[j]/s;}}Ok(Tensor{shape:self.shape.clone(),data:d,dtype:self.dtype})}}
pub fn transpose(&self)->Result<Tensor,AiError>{if self.rank()!=2{return Err(AiError::InvalidShape("transpose 2D".into()));}let(m,n)=(self.shape[0],self.shape[1]);let mut d=vec![0.0;m*n];for i in 0..m{for j in 0..n{d[j*m+i]=self.data[i*n+j];}}Ok(Tensor{shape:vec![n,m],data:d,dtype:self.dtype})}
pub fn mean(&self)->f64{if self.data.is_empty(){return 0.0;}self.data.iter().sum::<f64>()/self.data.len() as f64}
pub fn dot(&self,o:&Tensor)->Result<f64,AiError>{if self.rank()!=1||o.rank()!=1||self.data.len()!=o.data.len(){return Err(AiError::ShapeMismatch);}Ok(self.data.iter().zip(&o.data).map(|(a,b)|a*b).sum())}}
#[derive(Clone,Debug)] pub enum Activation{ReLU,Sigmoid,Tanh,Softmax,None_}
impl Activation{pub fn apply(&self,t:&Tensor)->Tensor{match self{Activation::ReLU=>t.relu(),Activation::Sigmoid=>t.sigmoid(),Activation::Tanh=>{Tensor{shape:t.shape.clone(),data:t.data.iter().map(|a|a.tanh()).collect(),dtype:t.dtype}}Activation::Softmax=>t.softmax().unwrap_or_else(|_|t.clone()),Activation::None_=>t.clone()}}pub fn name(&self)->&str{match self{Activation::ReLU=>"relu",Activation::Sigmoid=>"sigmoid",Activation::Tanh=>"tanh",Activation::Softmax=>"softmax",Activation::None_=>"none"}}}
#[derive(Clone,Debug)] pub struct Layer{pub weights:Tensor,pub bias:Tensor,pub activation:Activation,pub name:String,pub neuron_count:usize}
impl Layer{pub fn new(name:String,input_size:usize,output_size:usize,activation:Activation)->Self{let mut w=Vec::with_capacity(input_size*output_size);for i in 0..input_size*output_size{w.push(((i as u64*2654435761%1000) as f64/1000.0)-0.5);}Layer{weights:Tensor::new(vec![input_size,output_size],w),bias:Tensor::from_vec(vec![0.0;output_size]),activation,name,neuron_count:output_size}}
pub fn forward(&self,input:&Tensor)->Result<Tensor,AiError>{let i2d=if input.rank()==1{Tensor::new(vec![1,input.size()],input.data.clone())}else{input.clone()};let z=i2d.matmul(&self.weights)?;let mut od=z.data.clone();let n=z.shape[1];for i in 0..z.shape[0]{for j in 0..n{od[i*n+j]+=self.bias.data[j];}}let pa=Tensor::new(z.shape.clone(),od);Ok(self.activation.apply(&pa))}}
#[derive(Clone,Debug)] pub struct Model{pub id:String,pub name:String,pub model_type:ModelType,pub layers:Vec<Layer>,pub input_shape:Vec<usize>,pub output_shape:Vec<usize>,pub owner_did:String,pub inference_count:u64,pub total_gas_used:u64}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum ModelType{FeedForward,Llm,Classifier,Embedder,Custom}
impl ModelType{pub fn name(&self)->&str{match self{ModelType::FeedForward=>"feedforward",ModelType::Llm=>"llm",ModelType::Classifier=>"classifier",ModelType::Embedder=>"embedder",ModelType::Custom=>"custom"}}}
impl Model{pub fn new(id:String,name:String,model_type:ModelType,owner_did:String)->Self{Model{id,name,model_type,layers:Vec::new(),input_shape:vec![],output_shape:vec![],owner_did,inference_count:0,total_gas_used:0}}pub fn add_layer(&mut self,layer:Layer){if self.layers.is_empty(){self.input_shape=vec![layer.weights.shape[0]];}self.output_shape=vec![layer.neuron_count];self.layers.push(layer);}pub fn forward(&mut self,input:&Tensor,gas_cost:u64)->Result<Tensor,AiError>{if self.layers.is_empty(){return Err(AiError::ModelEmpty);}let mut c=input.clone();for layer in&self.layers{c=layer.forward(&c)?;}self.inference_count+=1;self.total_gas_used+=gas_cost;Ok(c)}pub fn layer_count(&self)->usize{self.layers.len()}pub fn param_count(&self)->usize{self.layers.iter().map(|l|l.weights.size()+l.bias.size()).sum()}}
pub struct ModelRegistry{models:Mutex<BTreeMap<String,Model>>,next_id:Mutex<u64>}
impl ModelRegistry{pub fn new()->Self{ModelRegistry{models:Mutex::new(BTreeMap::new()),next_id:Mutex::new(1)}}pub fn register(&self,mut m:Model)->String{if m.id.is_empty(){let id={let mut n=self.next_id.lock();let v=*n;*n+=1;v};m.id=format!("model:{}",id);}let id=m.id.clone();self.models.lock().insert(id.clone(),m);id}pub fn get(&self,id:&str)->Option<Model>{self.models.lock().get(id).cloned()}pub fn exists(&self,id:&str)->bool{self.models.lock().contains_key(id)}pub fn count(&self)->usize{self.models.lock().len()}pub fn run_inference(&self,id:&str,input:&Tensor,gas:u64)->Result<Tensor,AiError>{let mut m=self.models.lock();let model=m.get_mut(id).ok_or(AiError::ModelNotFound)?;model.forward(input,gas)}}}
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum AiCapability{Inference,Train,Deploy,Query,Delete,NeuralContext}
impl AiCapability{pub fn gas_cost(&self)->u64{match self{AiCapability::Inference=>10000,AiCapability::Train=>50000,AiCapability::Deploy=>20000,AiCapability::Query=>100,AiCapability::Delete=>1000,AiCapability::NeuralContext=>500}}pub fn name(&self)->&str{match self{AiCapability::Inference=>"ai:inference",AiCapability::Train=>"ai:train",AiCapability::Deploy=>"ai:deploy",AiCapability::Query=>"ai:query",AiCapability::Delete=>"ai:delete",AiCapability::NeuralContext=>"ai:neural_context"}}}
pub struct AiCapabilityGuard{granted:Mutex<BTreeMap<String,Vec<AiCapability>>>}
impl AiCapabilityGuard{pub fn new()->Self{AiCapabilityGuard{granted:Mutex::new(BTreeMap::new())}}pub fn grant(&self,did:&str,c:AiCapability){self.granted.lock().entry(did.to_string()).or_insert_with(Vec::new).push(c);}pub fn check(&self,did:&str,c:AiCapability)->bool{self.granted.lock().get(did).map(|cs|cs.contains(&c)).unwrap_or(false)}pub fn grant_all(&self,did:&str){self.granted.lock().insert(did.to_string(),vec![AiCapability::Inference,AiCapability::Train,AiCapability::Deploy,AiCapability::Query,AiCapability::Delete,AiCapability::NeuralContext]);}}
#[derive(Clone,Debug)] pub struct ContextEntry{pub id:u64,pub key:String,pub embedding:Vec<f64>,pub metadata:String,pub timestamp:u64,pub owner_did:String}
pub struct NeuralContextStore{entries:Mutex<BTreeMap<u64,ContextEntry>>,by_key:Mutex<BTreeMap<String,u64>>,next_id:Mutex<u64>}
impl NeuralContextStore{pub fn new()->Self{NeuralContextStore{entries:Mutex::new(BTreeMap::new()),by_key:Mutex::new(BTreeMap::new()),next_id:Mutex::new(1)}}pub fn store(&self,key:String,embedding:Vec<f64>,metadata:String,timestamp:u64,owner_did:String)->u64{let id={let mut n=self.next_id.lock();let v=*n;*n+=1;v};self.by_key.lock().insert(key.clone(),id);self.entries.lock().insert(id,ContextEntry{id,key,embedding,metadata,timestamp,owner_did});id}pub fn retrieve(&self,key:&str)->Option<ContextEntry>{let bk=self.by_key.lock();let id=bk.get(key)?;self.entries.lock().get(id).cloned()}pub fn count(&self)->usize{self.entries.lock().len()}pub fn similarity_search(&self,query:&[f64],top_k:usize)->Vec<(u64,f64)>{let e=self.entries.lock();let mut s:e.values().map(|x|(x.id,cosine_similarity(query,&x.embedding))).collect();s.sort_by(|a,b|b.1.partial_cmp(&a.1).unwrap_or(alloc::cmp::Ordering::Equal));s.into_iter().take(top_k).collect()}}
pub fn cosine_similarity(a:&[f64],b:&[f64])->f64{if a.len()!=b.len()||a.is_empty(){return 0.0;}let dot:a.iter().zip(b).map(|(x,y)|x*y).sum();let na:a.iter().map(|x|x*x).sum::<f64>().sqrt();let nb:b.iter().map(|x|x*x).sum::<f64>().sqrt();if na==0.0||nb==0.0{return 0.0;}dot/(na*nb)}
#[derive(Clone,Debug)] pub struct LlmRequest{pub prompt:String,pub max_tokens:u32,pub temperature:f64,pub model_id:Option<String>,pub caller_did:String}
#[derive(Clone,Debug)] pub struct LlmResponse{pub output:String,pub tokens_generated:u32,pub gas_used:u64,pub model_id:String}
pub struct LlmRouter{registry:Arc<ModelRegistry>,default_model:Mutex<Option<String>>}
impl LlmRouter{pub fn new(registry:Arc<ModelRegistry>)->Self{LlmRouter{registry,default_model:Mutex::new(None)}}pub fn set_default_model(&self,id:String){*self.default_model.lock()=Some(id);}pub fn infer(&self,req:LlmRequest)->Result<LlmResponse,AiError>{let mid=req.model_id.or_else(||self.default_model.lock().clone()).ok_or(AiError::NoDefaultModel)?;if!self.registry.exists(&mid){return Err(AiError::ModelNotFound);}let h=crate::security::simple_hash(req.prompt.as_bytes());let out=format!("ai:response:{:08x}",u64::from_be_bytes(h[..8].try_into().unwrap()));let tg=req.max_tokens.min(out.len() as u32/4);let gu=(tg as u64)*100;Ok(LlmResponse{output:out,tokens_generated:tg,gas_used:gu,model_id:mid})}}
pub struct AiEngine{pub models:Arc<ModelRegistry>,pub context:Arc<NeuralContextStore>,pub capabilities:Arc<AiCapabilityGuard>,pub llm_router:Arc<LlmRouter>}
impl AiEngine{pub fn new()->Self{let models=Arc::new(ModelRegistry::new());let context=Arc::new(NeuralContextStore::new());let caps=Arc::new(AiCapabilityGuard::new());let llm=Arc::new(LlmRouter::new(models.clone()));AiEngine{models,context,capabilities,llm_router:llm}}pub fn deploy_model(&self,model:Model,did:&str)->Result<String,AiError>{if!self.capabilities.check(did,AiCapability::Deploy){return Err(AiError::PermissionDenied);}Ok(self.models.register(model))}pub fn infer(&self,id:&str,input:&Tensor,did:&str,gas:u64)->Result<Tensor,AiError>{if!self.capabilities.check(did,AiCapability::Inference){return Err(AiError::PermissionDenied);}self.models.run_inference(id,input,AiCapability::Inference.gas_cost())}pub fn store_context(&self,key:String,emb:Vec<f64>,meta:String,ts:u64,did:&str)->Result<u64,AiError>{if!self.capabilities.check(did,AiCapability::NeuralContext){return Err(AiError::PermissionDenied);}Ok(self.context.store(key,emb,meta,ts,did.to_string()))}pub fn llm_infer(&self,req:LlmRequest)->Result<LlmResponse,AiError>{if!self.capabilities.check(&req.caller_did,AiCapability::Inference){return Err(AiError::PermissionDenied);}self.llm_router.infer(req)}pub fn model_count(&self)->usize{self.models.count()}pub fn context_count(&self)->usize{self.context.count()}}
#[derive(Debug,Clone,PartialEq,Eq)] pub enum AiError{ShapeMismatch,InvalidShape(String),ModelNotFound,ModelEmpty,NoDefaultModel,PermissionDenied,OutOfGas,InvalidInput}
