// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// K-Sprint 18 — Block-Proposal-Pipeline
use alloc::collections::BTreeMap; use alloc::vec::Vec; use alloc::string::{String,ToString}; use alloc::sync::Arc; use spin::Mutex;
use crate::mempool::{Transaction,TxStatus,TxType};
use crate::consensus::ConsensusEngine;
use crate::security::simple_hash;
#[derive(Clone,Debug)]
pub struct Block{pub id:[u8;32],pub height:u64,pub parent_hash:[u8;32],pub proposer_did:String,pub timestamp:u64,pub poh_hash:[u8;32],pub transactions:Vec<Transaction>,pub tx_root:[u8;32],pub state_root:[u8;32],pub gas_used:u64,pub total_fees:u64,pub signature:[u8;64]}
impl Block{pub fn new(height:u64,parent_hash:[u8;32],proposer_did:String,timestamp:u64,poh_hash:[u8;32],transactions:Vec<Transaction>,signature:[u8;64])->Self{let gas_used:u64=transactions.iter().map(|tx|tx.gas_cost()).sum();let total_fees:u64=transactions.iter().map(|tx|tx.max_fee()).sum();let mut ti=Vec::new();for tx in&transactions{ti.extend_from_slice(&tx.id);}let tx_root=simple_hash(&ti);let mut bi=Vec::new();bi.extend_from_slice(&height.to_be_bytes());bi.extend_from_slice(&parent_hash);bi.extend_from_slice(proposer_did.as_bytes());bi.extend_from_slice(&timestamp.to_be_bytes());bi.extend_from_slice(&poh_hash);bi.extend_from_slice(&tx_root);bi.extend_from_slice(&signature);let id=simple_hash(&bi);Block{id,height,parent_hash,proposer_did,timestamp,poh_hash,transactions,tx_root,state_root:[0u8;32],gas_used,total_fees,signature}}
pub fn tx_count(&self)->usize{self.transactions.len()} pub fn is_empty(&self)->bool{self.transactions.is_empty()}}
pub struct BlockChain{blocks:Mutex<BTreeMap<u64,Block>>,by_hash:Mutex<BTreeMap<[u8;32],u64>>,current_height:Mutex<u64>,genesis_hash:Mutex<Option<[u8;32]>>}
impl BlockChain{pub fn new()->Self{BlockChain{blocks:Mutex::new(BTreeMap::new()),by_hash:Mutex::new(BTreeMap::new()),current_height:Mutex::new(0),genesis_hash:Mutex::new(None)}}
pub fn add_genesis(&self,block:Block)->Result<(),PipelineError>{if block.height!=0{return Err(PipelineError::InvalidHeight);}let mut b=self.blocks.lock();if b.contains_key(&0){return Err(PipelineError::GenesisExists);}*self.genesis_hash.lock()=Some(block.id);self.by_hash.lock().insert(block.id,0);b.insert(0,block);*self.current_height.lock()=0;Ok(())}
pub fn add_block(&self,block:Block)->Result<(),PipelineError>{let mut b=self.blocks.lock();let mut bh=self.by_hash.lock();let mut h=self.current_height.lock();if block.height!=*h+1{return Err(PipelineError::InvalidHeight);}if b.contains_key(&block.height){return Err(PipelineError::BlockExists);}if bh.contains_key(&block.id){return Err(PipelineError::DuplicateBlock);}bh.insert(block.id,block.height);b.insert(block.height,block);*h=block.height;Ok(())}
pub fn get_block(&self,height:u64)->Option<Block>{self.blocks.lock().get(&height).cloned()} pub fn get_by_hash(&self,hash:&[u8;32])->Option<Block>{let bh=self.by_hash.lock();bh.get(hash).and_then(|&h|self.blocks.lock().get(&h).cloned())} pub fn current_height(&self)->u64{*self.current_height.lock()} pub fn block_count(&self)->usize{self.blocks.lock().len()} pub fn last_block(&self)->Option<Block>{let h=*self.current_height.lock();self.blocks.lock().get(&h).cloned()}}
pub struct ProposalPipeline{mempool:Arc<crate::mempool::MemoryPool>,validator:Arc<crate::mempool::TxValidator>,consensus:Arc<ConsensusEngine>,chain:Arc<BlockChain>,state:Arc<crate::mempool::StateDb>,our_did:String,block_height:Mutex<u64>}
impl ProposalPipeline{pub fn new(mempool:Arc<crate::mempool::MemoryPool>,validator:Arc<crate::mempool::TxValidator>,consensus:Arc<ConsensusEngine>,chain:Arc<BlockChain>,state:Arc<crate::mempool::StateDb>,our_did:String)->Self{ProposalPipeline{mempool,validator,consensus,chain,state,our_did,block_height:Mutex::new(0)}}
pub fn create_genesis(&self,timestamp:u64)->Result<Block,PipelineError>{let pe=self.consensus.poh().tick(timestamp);let g=Block::new(0,[0u8;32],self.our_did.clone(),timestamp,pe.hash,vec![],[0u8;64]);self.chain.add_genesis(g.clone())?;*self.block_height.lock()=0;Ok(g)}
pub fn propose_block(&self,max_txs:usize,timestamp:u64)->Result<Block,PipelineError>{let pending=self.mempool.get_pending_batch(max_txs);if pending.is_empty(){return Err(PipelineError::NoPendingTxs);}let mut valid=Vec::new();for tx in pending{if self.validator.validate(&tx).is_ok(){self.validator.apply(&tx).unwrap_or(());self.mempool.mark_in_dag(&tx.id);valid.push(tx);}}if valid.is_empty(){return Err(PipelineError::AllTxsInvalid);}let parent=self.chain.last_block().ok_or(PipelineError::NoGenesis)?;let pe=self.consensus.poh().tick(timestamp);let h=parent.height+1;let block=Block::new(h,parent.id,self.our_did.clone(),timestamp,pe.hash,valid,[0u8;64]);self.chain.add_block(block.clone())?;*self.block_height.lock()=h;let _=self.consensus.propose_vertex(block.id,timestamp,[0u8;64]).map_err(|_|PipelineError::DagInsertFailed)?;Ok(block)}
pub fn vote_on_block(&self,block_hash:[u8;32],timestamp:u64,approve:bool,signature:[u8;64]){self.consensus.vote(block_hash,timestamp,approve,signature);}
pub fn cleanup_mempool(&self,now:u64)->usize{self.mempool.cleanup(now)} pub fn chain(&self)->&Arc<BlockChain>{&self.chain} pub fn mempool(&self)->&Arc<crate::mempool::MemoryPool>{&self.mempool} pub fn consensus(&self)->&Arc<ConsensusEngine>{&self.consensus} pub fn state(&self)->&Arc<crate::mempool::StateDb>{&self.state} pub fn current_height(&self)->u64{*self.block_height.lock()}}
}
#[derive(Debug,Clone,PartialEq,Eq)] pub enum PipelineError{NoPendingTxs,AllTxsInvalid,NoGenesis,InvalidHeight,ParentNotFound,BlockExists,DuplicateBlock,GenesisExists,DagInsertFailed}
