// Copyright (c) 2026 Michael Wroblewski / ShivaCore / A-TownChain-Okosystems. All Rights Reserved.
// K-Sprint 17 — Memory-Pool & Transaction-Validation
use alloc::collections::BTreeMap; use alloc::vec::Vec; use alloc::string::{String,ToString}; use alloc::sync::Arc; use spin::Mutex;
#[derive(Clone,Copy,Debug,PartialEq,Eq)] #[repr(u8)]
pub enum TxType { Transfer=1,Stake=2,Unstake=3,Delegate=4,Vote=5,ContractCall=6,ContractDeploy=7 }
impl TxType { pub fn from_u8(v:u8)->Option<Self>{match v{1=>Some(TxType::Transfer),2=>Some(TxType::Stake),3=>Some(TxType::Unstake),4=>Some(TxType::Delegate),5=>Some(TxType::Vote),6=>Some(TxType::ContractCall),7=>Some(TxType::ContractDeploy),_=>None}} pub fn base_gas(&self)->u64{match self{TxType::Transfer=>1000,TxType::Stake=>2000,TxType::Unstake=>2000,TxType::Delegate=>1500,TxType::Vote=>500,TxType::ContractCall=>5000,TxType::ContractDeploy=>50000}} }
#[derive(Clone,Debug)]
pub struct Transaction { pub id:[u8;32],pub tx_type:TxType,pub sender_did:String,pub recipient_did:Option<String>,pub amount:u64,pub gas_price:u64,pub gas_limit:u64,pub nonce:u64,pub timestamp:u64,pub payload:Vec<u8>,pub signature:[u8;64],pub poh_hash:[u8;32] }
impl Transaction { pub fn new(tx_type:TxType,sender_did:String,recipient_did:Option<String>,amount:u64,gas_price:u64,gas_limit:u64,nonce:u64,timestamp:u64,payload:Vec<u8>,signature:[u8;64],poh_hash:[u8;32])->Self{let mut i=Vec::new();i.push(tx_type as u8);i.extend_from_slice(sender_did.as_bytes());if let Some(ref r)=recipient_did{i.extend_from_slice(r.as_bytes());}i.extend_from_slice(&amount.to_be_bytes());i.extend_from_slice(&gas_price.to_be_bytes());i.extend_from_slice(&gas_limit.to_be_bytes());i.extend_from_slice(&nonce.to_be_bytes());i.extend_from_slice(&timestamp.to_be_bytes());i.extend_from_slice(&poh_hash);i.extend_from_slice(&payload);let id=crate::security::simple_hash(&i);Transaction{id,tx_type,sender_did,recipient_did,amount,gas_price,gas_limit,nonce,timestamp,payload,signature,poh_hash}} pub fn gas_cost(&self)->u64{self.tx_type.base_gas()+(self.payload.len() as u64)*10} pub fn max_fee(&self)->u64{self.gas_limit.saturating_mul(self.gas_price)} pub fn payload_hash(&self)->[u8;32]{self.id} }
#[derive(Clone,Copy,Debug,PartialEq,Eq)] pub enum TxStatus{Pending,Validated,InDag,Confirmed,Rejected,Expired}
#[derive(Clone,Debug)] pub struct PoolEntry{pub tx:Transaction,pub status:TxStatus,pub added_at:u64,pub validated_at:Option<u64>,pub reject_reason:Option<String>,pub priority:u64}
pub struct MemoryPool{entries:Mutex<BTreeMap<[u8;32],PoolEntry>>,by_sender:Mutex<BTreeMap<String,Vec<[u8;32]>>>,max_size:usize,max_age_ns:u64}
impl MemoryPool{pub fn new(max_size:usize,max_age_secs:u64)->Self{MemoryPool{entries:Mutex::new(BTreeMap::new()),by_sender:Mutex::new(BTreeMap::new()),max_size,max_age_ns:max_age_secs*1_000_000_000}}
pub fn add(&self,tx:Transaction,now:u64)->Result<(),MempoolError>{let mut e=self.entries.lock();if e.len()>=self.max_size{return Err(MempoolError::PoolFull);}if e.contains_key(&tx.id){return Err(MempoolError::DuplicateTx);}let p=tx.gas_price.saturating_mul(tx.gas_limit);e.insert(tx.id,PoolEntry{tx:tx.clone(),status:TxStatus::Pending,added_at:now,validated_at:None,reject_reason:None,priority:p});self.by_sender.lock().entry(tx.sender_did.clone()).or_insert_with(Vec::new).push(tx.id);Ok(())}
pub fn validate_tx(&self,tx_id:&[u8;32],now:u64)->Result<(),MempoolError>{let mut e=self.entries.lock();let entry=e.get_mut(tx_id).ok_or(MempoolError::TxNotFound)?;if entry.tx.gas_limit<entry.tx.tx_type.base_gas(){entry.status=TxStatus::Rejected;return Err(MempoolError::GasLimitTooLow);}if entry.tx.amount>0&&entry.tx.recipient_did.is_none()&&entry.tx.tx_type==TxType::Transfer{entry.status=TxStatus::Rejected;return Err(MempoolError::NoRecipient);}if entry.tx.gas_price==0{entry.status=TxStatus::Rejected;return Err(MempoolError::ZeroGasPrice);}entry.status=TxStatus::Validated;entry.validated_at=Some(now);Ok(())}
pub fn get_pending_batch(&self,max_count:usize)->Vec<Transaction>{let e=self.entries.lock();let mut v:e.values().filter(|x|x.status==TxStatus::Validated).collect();v.sort_by(|a,b|b.priority.cmp(&a.priority));v.into_iter().take(max_count).map(|x|x.tx.clone()).collect()}
pub fn mark_in_dag(&self,tx_id:&[u8;32]){if let Some(e)=self.entries.lock().get_mut(tx_id){e.status=TxStatus::InDag;}}
pub fn mark_confirmed(&self,tx_id:&[u8;32]){if let Some(e)=self.entries.lock().get_mut(tx_id){e.status=TxStatus::Confirmed;}}
pub fn cleanup(&self,now:u64)->usize{let mut e=self.entries.lock();let mut bs=self.by_sender.lock();let rm:e.iter().filter(|(_,x|x.status==TxStatus::Confirmed||x.status==TxStatus::Rejected||(x.status==TxStatus::Pending&&(now-x.added_at)>self.max_age_ns)).map(|(k,_)|*k).collect();for t in&rm{if let Some(en)=e.remove(t){if let Some(txs)=bs.get_mut(&en.tx.sender_did){txs.retain(|x|x!=t);}}}rm.len()}
pub fn get(&self,tx_id:&[u8;32])->Option<PoolEntry>{self.entries.lock().get(tx_id).cloned()}
pub fn count(&self)->usize{self.entries.lock().len()} pub fn pending_count(&self)->usize{self.entries.lock().values().filter(|e|e.status==TxStatus::Pending).count()} pub fn validated_count(&self)->usize{self.entries.lock().values().filter(|e|e.status==TxStatus::Validated).count()} pub fn confirmed_count(&self)->usize{self.entries.lock().values().filter(|e|e.status==TxStatus::Confirmed).count()} pub fn rejected_count(&self)->usize{self.entries.lock().values().filter(|e|e.status==TxStatus::Rejected).count()}
pub fn txs_by_sender(&self,did:&str)->Vec<Transaction>{let bs=self.by_sender.lock();let e=self.entries.lock();bs.get(did).map(|ids|ids.iter().filter_map(|id|e.get(id).map(|x|x.tx.clone())).collect()).unwrap_or_default()}
pub fn sender_nonce(&self,did:&str)->u64{let bs=self.by_sender.lock();let e=self.entries.lock();bs.get(did).map(|ids|ids.iter().filter_map(|id|e.get(id).map(|x|x.tx.nonce)).max().unwrap_or(0)).unwrap_or(0)} }
pub struct NonceTracker{nonces:Mutex<BTreeMap<String,u64>>}
impl NonceTracker{pub fn new()->Self{NonceTracker{nonces:Mutex::new(BTreeMap::new())}}pub fn check_and_advance(&self,did:&str,nonce:u64)->bool{let mut n=self.nonces.lock();let e=n.entry(did.to_string()).or_insert(0);if nonce==*e{*e+=1;true}else{false}}pub fn expected_nonce(&self,did:&str)->u64{self.nonces.lock().get(did).copied().unwrap_or(0)}pub fn set_nonce(&self,did:&str,nonce:u64){self.nonces.lock().insert(did.to_string(),nonce);}pub fn reset(&self,did:&str){self.nonces.lock().remove(did);}}
#[derive(Clone,Debug)] pub struct Account{pub did:String,pub balance:u64,pub staked:u64,pub nonce:u64}
pub struct StateDb{accounts:Mutex<BTreeMap<String,Account>>}
impl StateDb{pub fn new()->Self{StateDb{accounts:Mutex::new(BTreeMap::new())}}pub fn get_balance(&self,did:&str)->u64{self.accounts.lock().get(did).map(|a|a.balance).unwrap_or(0)}pub fn get_staked(&self,did:&str)->u64{self.accounts.lock().get(did).map(|a|a.staked).unwrap_or(0)}pub fn get_nonce(&self,did:&str)->u64{self.accounts.lock().get(did).map(|a|a.nonce).unwrap_or(0)}pub fn deposit(&self,did:&str,amount:u64){let mut a=self.accounts.lock();let acc=a.entry(did.to_string()).or_insert(Account{did:did.to_string(),balance:0,staked:0,nonce:0});acc.balance+=amount;}pub fn withdraw(&self,did:&str,amount:u64)->Result<(),MempoolError>{let mut a=self.accounts.lock();let acc=a.entry(did.to_string()).or_insert(Account{did:did.to_string(),balance:0,staked:0,nonce:0});if acc.balance<amount{return Err(MempoolError::InsufficientBalance);}acc.balance-=amount;Ok(())}pub fn stake(&self,did:&str,amount:u64)->Result<(),MempoolError>{let mut a=self.accounts.lock();let acc=a.entry(did.to_string()).or_insert(Account{did:did.to_string(),balance:0,staked:0,nonce:0});if acc.balance<amount{return Err(MempoolError::InsufficientBalance);}acc.balance-=amount;acc.staked+=amount;Ok(())}pub fn unstake(&self,did:&str,amount:u64)->Result<(),MempoolError>{let mut a=self.accounts.lock();let acc=a.entry(did.to_string()).or_insert(Account{did:did.to_string(),balance:0,staked:0,nonce:0});if acc.staked<amount{return Err(MempoolError::InsufficientStake);}acc.staked-=amount;acc.balance+=amount;Ok(())}pub fn increment_nonce(&self,did:&str){let mut a=self.accounts.lock();let acc=a.entry(did.to_string()).or_insert(Account{did:did.to_string(),balance:0,staked:0,nonce:0});acc.nonce+=1;}pub fn total_supply(&self)->u64{self.accounts.lock().values().map(|a|a.balance+a.staked).sum()}}
pub struct TxValidator{state:Arc<StateDb>,nonces:Arc<NonceTracker>,min_gas_price:u64}
impl TxValidator{pub fn new(state:Arc<StateDb>,nonces:Arc<NonceTracker>,min_gas_price:u64)->Self{TxValidator{state,nonces,min_gas_price}}pub fn validate(&self,tx:&Transaction)->Result<(),MempoolError>{if tx.gas_price<self.min_gas_price{return Err(MempoolError::GasPriceTooLow);}if tx.gas_limit<tx.gas_cost(){return Err(MempoolError::GasLimitTooLow);}if tx.tx_type==TxType::Transfer&&tx.amount>0&&tx.recipient_did.is_none(){return Err(MempoolError::NoRecipient);}let en=self.nonces.expected_nonce(&tx.sender_did);if tx.nonce!=en{return Err(MempoolError::InvalidNonce{expected:en,got:tx.nonce});}if self.state.get_balance(&tx.sender_did)<tx.amount+tx.max_fee(){return Err(MempoolError::InsufficientBalance);}if tx.tx_type==TxType::Unstake&&self.state.get_staked(&tx.sender_did)<tx.amount{return Err(MempoolError::InsufficientStake);}Ok(())}pub fn apply(&self,tx:&Transaction)->Result<(),MempoolError>{self.state.withdraw(&tx.sender_did,tx.max_fee())?;match tx.tx_type{TxType::Transfer=>{let r=tx.recipient_did.as_ref().unwrap();self.state.withdraw(&tx.sender_did,tx.amount)?;self.state.deposit(r,tx.amount);}TxType::Stake=>{self.state.stake(&tx.sender_did,tx.amount)?;}TxType::Unstake=>{self.state.unstake(&tx.sender_did,tx.amount)?;}_=>{}}self.nonces.check_and_advance(&tx.sender_did,tx.nonce);self.state.increment_nonce(&tx.sender_did);Ok(())}}
#[derive(Debug,Clone,PartialEq,Eq)] pub enum MempoolError{PoolFull,DuplicateTx,TxNotFound,GasLimitTooLow,GasPriceTooLow,ZeroGasPrice,NoRecipient,InvalidNonce{expected:u64,got:u64},InsufficientBalance,InsufficientStake,Expired}
